### ISSUE TITLE
File index_m.html not found after setup of 1.0.41 on iobroker 3.1.6

### ISSUE THREAD

**Issue by hgehrts** [ioBroker/ioBroker.knx#114]
Hi!
I just updated to the latest release of the Adapter but since then, I# not getting any setup page. I only get this error message when I open the setup page:
File index_m.html not found
I tried iobroker upload knx with no luck
I tried  npm cache clean --force with no luck
I tried setting up the adapter multiple times.
What can I do here? It looks to me like a bug.

**Comment by hgehrts** [comment]
I just made a fresh new installation of iobroker on a fresh Ubuntu lts vm, directly chosed the KNX adapter from github - and I got the same error on that new box. This is a bug.

**Comment by GRaptor** [comment]
Same with me

**Comment by hgehrts** [comment]
Hi @GRaptor , nice... the thing is: the knxproj doesn't work with 1.0.39:
2020-09-02 13:03:18.700  - warn: knx.0 (58870) States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":306,"ack":false,"time":1599044598631},"_id":83519955} Cannot read property 'toLowerCase' of undefined
2020-09-02 13:03:18.701  - warn: knx.0 (58870) TypeError: Cannot read property 'toLowerCase' of undefined
    at _0x128d60 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:22258)
    at _0x12ce32 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:22441)
    at _0x31f044 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:36762)
    at Object._0x3a7cff [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:40602)
    at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13499)
    at _0x465449 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8493)
    at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:7072)
    at Adapter.emit (events.js:198:13)
    at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5313:34)
    at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:234:41)

**Comment by hgehrts** [comment]
Issue ist gelöst. Im offiziellen Repo ist die 1.0.42, damit ging bei mir die Konfig Seite wieder und auch der knxproj Import.
