### ISSUE TITLE
States system pmessage io.messagebox.system.adapter.knx.0

### ISSUE THREAD

**Issue by rettroo** [ioBroker/ioBroker.knx#168]
Hallo,

trotz update auf 1.0.45 kann ich keine *.knxproj importieren von ETS 5.4.7. 

`

knx.0 | 2021-04-29 20:43:40.330 | warn | at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
knx.0 | 2021-04-29 20:43:40.330 | warn | at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37)
knx.0 | 2021-04-29 20:43:40.330 | warn | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5483:34)
knx.0 | 2021-04-29 20:43:40.330 | warn | at Adapter.emit (events.js:314:20)
knx.0 | 2021-04-29 20:43:40.330 | warn | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:300187)
knx.0 | 2021-04-29 20:43:40.330 | warn | at _0xd16195 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:301540)
knx.0 | 2021-04-29 20:43:40.330 | warn | at Object._0x134ddf [as getGAS] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:281218)
knx.0 | 2021-04-29 20:43:40.330 | warn | at Object._0x1cf485 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:266851)
knx.0 | 2021-04-29 20:43:40.330 | warn | at _0x597b31 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:248563)
knx.0 | 2021-04-29 20:43:40.330 | warn | (8534) TypeError: Cannot read property 'GroupRanges' of undefined
knx.0 | 2021-04-29 20:43:40.329 | warn | (8534) States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":803,"ack":false,"time":161

`

**Comment by rettroo** [comment]
please delete
