### ISSUE TITLE
Ohne Fehlermeldung keine Funktioon mehr

### ISSUE THREAD

**Issue by papper371** [ioBroker/ioBroker.knx#17]
Mein KNX Adapter / Instanz stellt ohne nachvollziehberen Grund den Dienst ein. Es macht sich erst bemerkbar wenn KNX Befehle gesendet werden sollen und die Aktoren nicht reagieren. Dann hilft ein "Neu lden" der Instanz nicht weiter. Die Instanz muss gestoppt und dann wieder neu gestartet werden. Dannach findet man folgende Einträge im Log:

knx.0 | 2018-03-01 09:42:51.310 | info | Connected!
-- | -- | -- | --
knx.0 | 2018-03-01 09:42:51.070 | info | /opt/iobroker/node_modules/iobroker.js-controller
knx.0 | 2018-03-01 09:42:51.069 | info | Connecting to knx GW: 192.168.178.40:3671 with phy. Adr: 15.15.250 and SendDelay of : 50 ms
knx.0 | 2018-03-01 09:42:51.069 | info | starting. Version 0.8.6 in /opt/iobroker/node_modules/iobroker.knx, node: v8.9.4
host.raspberrypi | 2018-03-01 09:42:49.305 | info | instance system.adapter.knx.0 terminated with code 6 (uncaught exception)
Caught | 2018-03-01 09:42:49.305 | error | by controller[0]: at Object.onceWrapper (events.js:315:30)
Caught | 2018-03-01 09:42:49.305 | error | by controller[0]: at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4692:21)
Caught | 2018-03-01 09:42:49.305 | error | by controller[0]: at Object.unload (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:11129)
Caught | 2018-03-01 09:42:49.305 | error | by controller[0]: at fsm.FSM.Disconnect (/opt/iobroker/node_modules/iobroker.knx/lib/knx-mod/src/Connection.js:252:8)
Caught | 2018-03-01 09:42:49.305 | error | by controller[0]: at fsm.Fsm.(anonymous function) [as transition] (/opt/iobroker/node_modules/machina/lib/machina.js:466:63)
Caught | 2018-03-01 09:42:49.304 | error | by controller[0]: at fsm.transition (/opt/iobroker/node_modules/machina/lib/machina.js:653:28)
Caught | 2018-03-01 09:42:49.304 | error | by controller[0]: at fsm._onEnter (/opt/iobroker/node_modules/iobroker.knx/lib/knx-mod/src/FSM.js:118:14)
Caught | 2018-03-01 09:42:49.304 | error | by controller[0]: at fsm.FSM.send (/opt/iobroker/node_modules/iobroker.knx/lib/knx-mod/src/Connection.js:186:15)
Caught | 2018-03-01 09:42:49.304 | error | by controller[0]: at Socket.send (dgram.js:435:8)
Caught | 2018-03-01 09:42:49.304 | error | by controller[0]: at Socket._healthCheck (dgram.js:637:11)
Caught | 2018-03-01 09:42:49.304 | error | by controller[0]: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
host.raspberrypi | 2018-03-01 09:42:49.237 | info | instance system.adapter.knx.0 started with pid 4785
host.raspberrypi | 2018-03-01 09:42:49.207 | info | object change system.adapter.knx.0
host.raspberrypi | 2018-03-01 09:42:48.189 | info | stopInstance system.adapter.knx.0 killing pid 1843
host.raspberrypi | 2018-03-01 09:42:48.188 | info | stopInstance system.adapter.knx.0
host.raspberrypi | 2018-03-01 09:42:48.187 | info | object change system.adapter.knx.0

ioBroker läuft auf einem neuen Raspberry pi 3 mit 64 GB Karte. Version Admin 2.0.9, KNX 0.8.6
Kann jemand helfen? Wo liegt der Fehler?

**Comment by chefkoch009** [comment]
Hallo papper371,

bitte aktualisiere Deinen js-controller:
#cd /opt/iobroker
#sudo npm cache clean
#sudo iobroker stop
#sudo npm install iobroker.js-controller
#sudo iobroker start

dann den Admin aktualisieren auf 3.2.0 und anschliessend den KNX Adapter. 

Wegen der Fehlermeldungen (bei Dir mit dem TS: 2018-03-01 09:42:49.304 ) habe ich den KNX-Stack neu geschrieben. Dieser Fehler taucht definitiv nicht mehr auf in der neuen Version.

VG
chefkoch009

**Comment by papper371** [comment]
Vielen Dank chefkoch009. Setze mich sofort daran und berichte dir per PN

Gruß

Dir

Gesendet von Mail für Windows 10

Von: chefkoch009
Gesendet: Donnerstag, 1. März 2018 12:55
An: ioBroker/ioBroker.knx
Cc: papper371; Author
Betreff: Re: [ioBroker/ioBroker.knx] Ohne Fehlermeldung keine Funktion mehr(#17)

Hallo papper371,
bitte aktualisiere Deinen js-controller:
#cd /opt/iobroker
#sudo npm cache clean
#sudo iobroker stop
#sudo npm install iobroker.js-controller
#sudo iobroker start
dann den Admin aktualisieren auf 3.2.0 und anschliessend den KNX Adapter.
Wegen der Fehlermeldungen (bei Dir mit dem TS: 2018-03-01 09:42:49.304 ) habe ich den KNX-Stack neu geschrieben. Dieser Fehler taucht definitiv nicht mehr auf in der neuen Version.
VG
chefkoch009

**Comment by papper371** [comment]
Hallo chefkoch009,
soweit ist alles in Ordnung. Jetzt sagt er mir aber, dass die Lizenz fehlt. Wo kann ich diese dem Adapter übergeben? Bei der Cloud kann man diese ja in das Fenster kopieren. Aber wo geht das im KNX Adapter?

Gruß

Dirk 

Gesendet von Mail für Windows 10

Von: chefkoch009
Gesendet: Donnerstag, 1. März 2018 12:55
An: ioBroker/ioBroker.knx
Cc: papper371; Author
Betreff: Re: [ioBroker/ioBroker.knx] Ohne Fehlermeldung keine Funktion mehr(#17)

Hallo papper371,
bitte aktualisiere Deinen js-controller:
#cd /opt/iobroker
#sudo npm cache clean
#sudo iobroker stop
#sudo npm install iobroker.js-controller
#sudo iobroker start
dann den Admin aktualisieren auf 3.2.0 und anschliessend den KNX Adapter.
Wegen der Fehlermeldungen (bei Dir mit dem TS: 2018-03-01 09:42:49.304 ) habe ich den KNX-Stack neu geschrieben. Dieser Fehler taucht definitiv nicht mehr auf in der neuen Version.
VG
chefkoch009

**Comment by chefkoch009** [comment]
Das ist ja schön zu hören.

In der KNX Adapterkonfiguration gibt es als 2. Reiter das Feld Lizens. Dort wird die knx-Lizens hinkopiert.

Im ioBrokerforum lautet der thread rund um den Adapter: http://forum.iobroker.net/viewtopic.php?p=129502

Dort bin ich ggf auch per PN erreichbar.

Wenn dieser issue erledigt ist, dann schliesse ihn bitte.

**Comment by papper371** [comment]
Leider sehe ich keinen 2. Reiter in der Konfiguration. Version 1.0.4

Am 01.03.2018 14:45 schrieb "chefkoch009" <notifications@github.com>:

**Comment by chefkoch009** [comment]
das habe ich hier: http://forum.iobroker.net/viewtopic.php?f=36&t=3934&p=129587#p129587
beschrieben wie das geht.

**Comment by papper371** [comment]
Hallo nochmal,
er zeigte mir zwar die Version 1.0.4 an, jedoch musste ich noch mal ein Upload starten. Dann hatte ich den 2. Reiter. Vorher hatte ich in der Konfiguration des Adapters vom Bild her noch die Version 0.8.6. Die Instanz läuft jetzt mit der Lizenz. Habe mein Projekt geladen bekomme aber in den Objekten der Rollladen nur leere States.



Eigentlich hatte ich den State für die Rollladen Auf/Ab im Bad angeklickt. Bekommen aber lt. Überschrift die Beleuchtung im Bad angezeigt.



Der richtige State zum Bad Decke schalten ist gefüllt


Anbei schicke ich dir noch mein knxproj.

Gruß

Dirk

Von: chefkoch009
Gesendet: Donnerstag, 1. März 2018 15:28
An: ioBroker/ioBroker.knx
Cc: papper371; Author
Betreff: Re: [ioBroker/ioBroker.knx] Ohne Fehlermeldung keine Funktion mehr(#17)

das habe ich hier: http://forum.iobroker.net/viewtopic.php?f=36&t=3934&p=129587#p129587
beschrieben wie das geht.

**Comment by chefkoch009** [comment]
Das liegt an dem "/" zwischen Auf/Ab. Hab das gerade gefixt. Die neue Version werde ich vermutl. heute Abend online stellen.

**Comment by papper371** [comment]
Vielen dank chefkoch009. Du hast mir heute super weitergeholfen. Vielen
Dank für diese prompte Hilfe.

Einen schönen Abend noch.

Gruß Dirk

chefkoch009 <notifications@github.com> schrieb am Do., 1. März 2018, 17:23:

**Comment by papper371** [comment]
Hallo chefkoch009,
leider habe ich noch immer keine Funktion. Die leeren States sind jetzt gefüllt (zumindest auf den ersten Blick). Folgende Fehler im LOG:


  |   |   |  
-- | -- | -- | --
knx.0 | 2018-03-02 09:43:33.120 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2018-03-02 09:43:33.120 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
knx.0 | 2018-03-02 09:43:33.120 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2018-03-02 09:43:33.120 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2018-03-02 09:43:33.120 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
knx.0 | 2018-03-02 09:43:33.120 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
knx.0 | 2018-03-02 09:43:33.120 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:81:1860)
knx.0 | 2018-03-02 09:43:33.120 | error | at _0x5b50ba.(anonymous function).write (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:749)
knx.0 | 2018-03-02 09:43:33.120 | error | at _0x5ee457.(anonymous function) [as groupValueWrite] (/opt/iobroker/node_modules/iobroker.knx/knx.js:17:32480)
knx.0 | 2018-03-02 09:43:33.120 | error | at Object.decodeVal (/opt/iobroker/node_modules/iobroker.knx/knx.js:31:27239)
knx.0 | 2018-03-02 09:43:33.120 | error | Error: unkown Inputvalue!
knx.0 | 2018-03-02 09:43:33.119 | error | message knx.0.Beleuchtung.DG.Kind_schalten [object Object] unkown Inputvalue!
knx.0 | 2018-03-02 09:42:24.872 | error | at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2018-03-02 09:42:24.872 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
knx.0 | 2018-03-02 09:42:24.872 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2018-03-02 09:42:24.872 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2018-03-02 09:42:24.872 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
knx.0 | 2018-03-02 09:42:24.872 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2018-03-02 09:42:24.872 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2018-03-02 09:42:24.872 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
knx.0 | 2018-03-02 09:42:24.872 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
knx.0 | 2018-03-02 09:42:24.872 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:81:1017)
knx.0 | 2018-03-02 09:42:24.872 | error | TypeError: Cannot read property 'knx.0.Rollladen.DG.Bad_Auf/Ab' of null
knx.0 | 2018-03-02 09:42:24.838 | error | message knx.0.Rollladen.DG.Bad_Auf/Ab null Cannot read property 'knx.0.Rollladen.DG.Bad_Auf/Ab' of null
knx.0 | 2018-03-02 09:42:02.787 | info | Connected!
knx.0 | 2018-03-02 09:42:02.690 | info | /opt/iobroker/node_modules/iobroker.js-controller
knx.0 | 2018-03-02 09:42:02.689 | info | Connecting to knx GW: 192.168.178.40:3671 with phy. Adr: 15.15.250
knx.0 | 2018-03-02 09:42:02.685 | info | knx license is OK.
knx.0 | 2018-03-02 09:42:02.400 | info | starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.knx, node: v8.9.4
host.raspberrypi | 2018-03-02 09:42:00.539 | info | instance system.adapter.knx.0 started with pid 5541
host.raspberrypi | 2018-03-02 09:41:30.512 | info | Restart adapter system.adapter.knx.0 because enabled
host.raspberrypi | 2018-03-02 09:41:30.511 | error | instance system.adapter.knx.0 terminated with code 156 ()

**Comment by chefkoch009** [comment]
z.Zt funktioniert das nur bei einem kompletten Neuimport des Projektes.

**Comment by papper371** [comment]
Hallo chefkoch009,
habe alles gemacht. Adapter mit Version 1.0.5 installiert Upload des Adapters. Alle Objekte des Adapters gelöscht und wieder Importiert. Leider trotzdem keinen Erfolg. Nach Import hatte ich zuerst nur eine Fehlermeldung 2018-03-02 10:56:16.592. Habe dann versucht den Adapter neu zu laden ohne Ergebnis. Danach gestoppt und wieder gestartet. Zwischentzeitlich mit ETS den Bus abgehört. Alles ohne Erfolg.

Hier das Log:


host.raspberrypi | 2018-03-02 11:00:00.093 | info | instance system.adapter.weatherunderground.0 started with pid 11436
-- | -- | -- | --
host.raspberrypi | 2018-03-02 11:00:00.044 | info | instance system.adapter.dwd.0 started with pid 11429
knx.0 | 2018-03-02 10:59:10.564 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2018-03-02 10:59:10.564 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
knx.0 | 2018-03-02 10:59:10.564 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2018-03-02 10:59:10.564 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2018-03-02 10:59:10.564 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
knx.0 | 2018-03-02 10:59:10.564 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
knx.0 | 2018-03-02 10:59:10.564 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:81:1860)
knx.0 | 2018-03-02 10:59:10.564 | error | at _0x5b50ba.(anonymous function).write (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:749)
knx.0 | 2018-03-02 10:59:10.564 | error | at _0x5ee457.(anonymous function) [as groupValueWrite] (/opt/iobroker/node_modules/iobroker.knx/knx.js:17:32480)
knx.0 | 2018-03-02 10:59:10.564 | error | at Object.decodeVal (/opt/iobroker/node_modules/iobroker.knx/knx.js:31:27239)
knx.0 | 2018-03-02 10:59:10.564 | error | Error: unkown Inputvalue!
knx.0 | 2018-03-02 10:59:10.532 | error | message knx.0.Beleuchtung.DG.Kind_schalten [object Object] unkown Inputvalue!
knx.0 | 2018-03-02 10:58:58.181 | info | Connected!
knx.0 | 2018-03-02 10:58:58.081 | info | /opt/iobroker/node_modules/iobroker.js-controller
knx.0 | 2018-03-02 10:58:58.080 | info | Connecting to knx GW: 192.168.178.40:3671 with phy. Adr: 15.15.250
knx.0 | 2018-03-02 10:58:58.076 | info | knx license is OK.
knx.0 | 2018-03-02 10:58:57.805 | info | starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.knx, node: v8.9.4
host.raspberrypi | 2018-03-02 10:58:55.906 | info | instance system.adapter.knx.0 started with pid 11360
host.raspberrypi | 2018-03-02 10:58:53.399 | info | instance system.adapter.knx.0 terminated with code null ()
host.raspberrypi | 2018-03-02 10:58:53.398 | warn | instance system.adapter.knx.0 terminated due to SIGTERM
host.raspberrypi | 2018-03-02 10:58:53.379 | info | stopInstance system.adapter.knx.0 killing pid 11353
host.raspberrypi | 2018-03-02 10:58:53.379 | info | stopInstance system.adapter.knx.0
host.raspberrypi | 2018-03-02 10:58:53.378 | info | object change system.adapter.knx.0
host.raspberrypi | 2018-03-02 10:58:51.150 | info | object change system.adapter.knx.0
host.raspberrypi | 2018-03-02 10:58:49.700 | info | instance system.adapter.knx.0 terminated with code 0 (OK)
knx.0 | 2018-03-02 10:58:49.662 | info | terminating
host.raspberrypi | 2018-03-02 10:58:49.642 | info | stopInstance system.adapter.knx.0 killing pid 11294
host.raspberrypi | 2018-03-02 10:58:49.642 | info | stopInstance system.adapter.knx.0
host.raspberrypi | 2018-03-02 10:58:49.640 | info | object change system.adapter.knx.0
knx.0 | 2018-03-02 10:58:21.716 | info | Connected!
knx.0 | 2018-03-02 10:58:21.565 | info | /opt/iobroker/node_modules/iobroker.js-controller
knx.0 | 2018-03-02 10:58:21.565 | info | Connecting to knx GW: 192.168.178.40:3671 with phy. Adr: 15.15.250
knx.0 | 2018-03-02 10:58:21.560 | info | knx license is OK.
knx.0 | 2018-03-02 10:58:21.274 | info | starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.knx, node: v8.9.4
host.raspberrypi | 2018-03-02 10:58:19.400 | info | instance system.adapter.knx.0 started with pid 11294
host.raspberrypi | 2018-03-02 10:58:16.923 | info | instance system.adapter.knx.0 terminated with code 0 (OK)
knx.0 | 2018-03-02 10:58:16.890 | info | terminating
host.raspberrypi | 2018-03-02 10:58:16.867 | info | stopInstance system.adapter.knx.0 killing pid 11212
host.raspberrypi | 2018-03-02 10:58:16.866 | info | stopInstance system.adapter.knx.0
host.raspberrypi | 2018-03-02 10:58:16.861 | info | object change system.adapter.knx.0
knx.0 | 2018-03-02 10:57:58.991 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2018-03-02 10:57:58.991 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
knx.0 | 2018-03-02 10:57:58.991 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2018-03-02 10:57:58.991 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2018-03-02 10:57:58.991 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
knx.0 | 2018-03-02 10:57:58.991 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
knx.0 | 2018-03-02 10:57:58.991 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:81:1860)
knx.0 | 2018-03-02 10:57:58.991 | error | at _0x5b50ba.(anonymous function).write (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:749)
knx.0 | 2018-03-02 10:57:58.991 | error | at _0x5ee457.(anonymous function) [as groupValueWrite] (/opt/iobroker/node_modules/iobroker.knx/knx.js:17:32480)
knx.0 | 2018-03-02 10:57:58.991 | error | at Object.decodeVal (/opt/iobroker/node_modules/iobroker.knx/knx.js:31:27239)
knx.0 | 2018-03-02 10:57:58.991 | error | Error: unkown Inputvalue!
knx.0 | 2018-03-02 10:57:58.989 | error | message knx.0.Beleuchtung.DG.Kind_schalten [object Object] unkown Inputvalue!
knx.0 | 2018-03-02 10:57:54.969 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2018-03-02 10:57:54.969 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
knx.0 | 2018-03-02 10:57:54.969 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2018-03-02 10:57:54.969 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2018-03-02 10:57:54.969 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
knx.0 | 2018-03-02 10:57:54.969 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
knx.0 | 2018-03-02 10:57:54.969 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:81:1860)
knx.0 | 2018-03-02 10:57:54.969 | error | at _0x5b50ba.(anonymous function).write (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:749)
knx.0 | 2018-03-02 10:57:54.969 | error | at _0x5ee457.(anonymous function) [as groupValueWrite] (/opt/iobroker/node_modules/iobroker.knx/knx.js:17:32480)
knx.0 | 2018-03-02 10:57:54.969 | error | at Object.decodeVal (/opt/iobroker/node_modules/iobroker.knx/knx.js:31:27239)
knx.0 | 2018-03-02 10:57:54.969 | error | Error: unkown Inputvalue!
knx.0 | 2018-03-02 10:57:54.967 | error | message knx.0.Beleuchtung.DG.Kind_schalten [object Object] unkown Inputvalue!
javascript.0 | 2018-03-02 10:56:51.204 | warn | at Object. (script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach:294:72)
javascript.0 | 2018-03-02 10:56:51.203 | warn | at controlTerrasse (script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach:247:13)
javascript.0 | 2018-03-02 10:56:51.200 | warn | State "knx.0.Rollladen.EG.Wohnen_T_Auf/Ab" not found
javascript.0 | 2018-03-02 10:56:51.200 | info | script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach: Sperre inaktiv, Rolladen folgen dem aktuellen Status: 0
javascript.0 | 2018-03-02 10:56:51.199 | info | script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach: Status Sperren = Strom: 0, Licht: 0, Manuell: 0, Sperre inaktiv: true
javascript.0 | 2018-03-02 10:56:51.126 | warn | at Object. (script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach:293:70)
javascript.0 | 2018-03-02 10:56:51.126 | warn | at controlTerrasse (script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach:247:13)
javascript.0 | 2018-03-02 10:56:51.123 | warn | State "knx.0.Rollladen.EG.Wohnen_T_Auf/Ab" not found
javascript.0 | 2018-03-02 10:56:51.122 | info | script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach: Sperre inaktiv, Rolladen folgen dem aktuellen Status: 0
javascript.0 | 2018-03-02 10:56:51.122 | info | script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach: Status Sperren = Strom: 0, Licht: null, Manuell: 0, Sperre inaktiv: true
javascript.0 | 2018-03-02 10:56:51.122 | warn | at Object. (script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach:293:70)
javascript.0 | 2018-03-02 10:56:51.122 | warn | at controlTerrasse (script.js.Steuerung.Rolladen.01_Rolladen_SteuerungEinfach:238:31)
javascript.0 | 2018-03-02 10:56:51.118 | warn | getState "knx.0.Beleuchtung.Garten.Außenbeleuchtung_schaltenR" not found (3)
knx.0 | 2018-03-02 10:56:51.054 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2018-03-02 10:56:51.054 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
knx.0 | 2018-03-02 10:56:51.054 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2018-03-02 10:56:51.054 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2018-03-02 10:56:51.054 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
knx.0 | 2018-03-02 10:56:51.054 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
knx.0 | 2018-03-02 10:56:51.054 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:81:1860)
knx.0 | 2018-03-02 10:56:51.054 | error | at _0x5b50ba.(anonymous function).write (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:749)
knx.0 | 2018-03-02 10:56:51.054 | error | at _0x5ee457.(anonymous function) [as groupValueWrite] (/opt/iobroker/node_modules/iobroker.knx/knx.js:17:32480)
knx.0 | 2018-03-02 10:56:51.054 | error | at Object.decodeVal (/opt/iobroker/node_modules/iobroker.knx/knx.js:31:27239)
knx.0 | 2018-03-02 10:56:51.054 | error | Error: unkown Inputvalue!
knx.0 | 2018-03-02 10:56:51.022 | error | message knx.0.Beleuchtung.DG.Kind_schalten [object Object] unkown Inputvalue!
knx.0 | 2018-03-02 10:56:48.870 | info | Connected!
knx.0 | 2018-03-02 10:56:48.771 | info | /opt/iobroker/node_modules/iobroker.js-controller
knx.0 | 2018-03-02 10:56:48.770 | info | Connecting to knx GW: 192.168.178.40:3671 with phy. Adr: 15.15.250
knx.0 | 2018-03-02 10:56:48.766 | info | knx license is OK.
knx.0 | 2018-03-02 10:56:48.468 | info | starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.knx, node: v8.9.4
host.raspberrypi | 2018-03-02 10:56:46.619 | info | instance system.adapter.knx.0 started with pid 11212
host.raspberrypi | 2018-03-02 10:56:16.593 | info | Restart adapter system.adapter.knx.0 because enabled
host.raspberrypi | 2018-03-02 10:56:16.592 | error | instance system.adapter.knx.0 terminated with code 156 ()
host.raspberrypi | 2018-03-02 10:55:03.183 | info | instance system.adapter.dwd.0 terminated with code 0 (OK)

Gruß

Dirk

**Comment by chefkoch009** [comment]
kann ich mir das knx projekt einmal anschauen? gern per AnyDesk.
