### ISSUE TITLE
Adapter stellt keine Verbindung her

### ISSUE THREAD

**Issue by tom3386** [ioBroker/ioBroker.knx#283]
Hallo @all, ich habe seit dem Update auf die letzte Version das Problem, dass der Adapter keine Verbindung mehr herstellt. Das schaut so aus:
![Bildschirmfoto 2023-04-23 um 09 52 19](https://user-images.githubusercontent.com/131580986/233827152-0becfad9-c91c-4b19-9204-0739bf25d6ff.png)

Die Einstellungen im Adapter müssten passen. 
![Bildschirmfoto 2023-04-23 um 09 53 53](https://user-images.githubusercontent.com/131580986/233827181-394bd5d8-a02f-4b4b-b115-10e4b82a0ac7.png)

Und ich bekomme ständig folgende Fehlermeldungen:

host.iobroker | 2023-04-23 09:49:33.520 | warn | Do not restart adapter system.adapter.knx.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2023-04-23 09:49:33.519 | error | instance system.adapter.knx.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
knx.0 | 2023-04-23 09:49:32.949 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
knx.0 | 2023-04-23 09:49:32.873 | error | Cannot read property 'val' of null
knx.0 | 2023-04-23 09:49:32.872 | error | TypeError: Cannot read property 'val' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:354959) at processImmediate (internal/timers.js:466:21)
knx.0 | 2023-04-23 09:49:32.866 | error | uncaught exception: Cannot read property 'val' of null

Alle Adapter sind auf neusten Stand. Das System auch. Hat jemand einen Tipp für mich, was ich tun kann?
Viele Grüße
Tom

**Comment by tom3386** [comment]
Hey, ich hab mal versucht eine weitere Instand zu installieren, dann kommen diese Fehlermeldungen - kann mir jemand helfen? 


2023-04-28 23:14:50.570 | error | instance system.adapter.knx.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | --
host.iobroker | 2023-04-28 23:14:50.569 | error | Caught by controller[0]: at processImmediate (internal/timers.js:466:21)
host.iobroker | 2023-04-28 23:14:50.569 | error | Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:354959)
host.iobroker | 2023-04-28 23:14:50.569 | error | Caught by controller[0]: TypeError: Cannot read property 'val' of null
knx.1 | 2023-04-28 23:14:50.309 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
knx.1 | 2023-04-28 23:14:50.158 | error | Cannot read property 'val' of null
knx.1 | 2023-04-28 23:14:50.157 | error | TypeError: Cannot read property 'val' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:354959) at processImmediate (internal/timers.js:466:21)
knx.1 | 2023-04-28 23:14:50.156 | error | uncaught exception: Cannot read property 'val' of null

**Comment by tom3386** [comment]
Hey, ich hab mal versucht eine weitere Instanz eingerichtet und dann kommen diese Fehlermeldungen. Wer hat eine Lösung?

<div class="MuiGrid-root MuiGrid-container MuiGrid-item css-n6nfem" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; display: flex; flex-flow: row wrap; width: 1713.25px; margin: 0px; -webkit-box-align: center; align-items: center; max-width: none;"><p class="MuiTypography-root MuiTypography-body2 iob4067 css-68o8xu" title="Geschätzte Größe" style="box-sizing: inherit; margin: 0px 1rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; font-size: 0.875rem; line-height: 1.43; letter-spacing: 0.01071em;">Log-Größe:<span class="Apple-converted-space"> </span><span class="iob4068" style="box-sizing: inherit; font-style: italic;">2.2 MB</span></p></div><div class="MuiGrid-root MuiGrid-item iob4088 css-1wxaqej" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px; flex-direction: row; height: 824px; overflow: hidden; max-width: none;"><div class="MuiTableContainer-root iob4044 css-kge0eu" style="box-sizing: inherit; width: 1713.25px; overflow-x: auto; height: 824px; caret-color: rgba(0, 0, 0, 0.87); color: rgba(0, 0, 0, 0.87); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">

Quelle | Zeit | warn | Nachricht
-- | -- | -- | --
host.iobroker | 2023-04-28 23:14:50.570 | error | instance system.adapter.knx.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-04-28 23:14:50.569 | error | Caught by controller[0]: at processImmediate (internal/timers.js:466:21)
host.iobroker | 2023-04-28 23:14:50.569 | error | Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:354959)
host.iobroker | 2023-04-28 23:14:50.569 | error | Caught by controller[0]: TypeError: Cannot read property 'val' of null
knx.1 | 2023-04-28 23:14:50.309 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
knx.1 | 2023-04-28 23:14:50.158 | error | Cannot read property 'val' of null
knx.1 | 2023-04-28 23:14:50.157 | error | TypeError: Cannot read property 'val' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:354959) at processImmediate (internal/timers.js:466:21)
 

</div><br class="Apple-interchange-newline"></div>

**Comment by chefkoch009** [comment]
ist das problem mit V2.0.22 gelöst?

**Comment by tom3386** [comment]
… leider nein.

**Comment by martin-afh** [comment]
> … leider nein.

Konntest du das Problem bereits lösen? Ich habe heute seit einem RaspPi Neustart das gleiche Problem. Allerdings bekomme ich eine 2. Instanz fehlerfrei zum Laufen.

**Comment by chefkoch009** [comment]
Auch nicht mit der letzten Version? Hast du mal iob u knx versucht?

**Comment by martin-afh** [comment]
Habe alles auf die allerneuste Version geupfated.

**Comment by chefkoch009** [comment]
Ich kann es nicht nachstellen. Aus diesem Grund biete ich dir eine Remote-Session an.

**Comment by martin-afh** [comment]
Das wäre bestimmt hilfreich. Was brauche ich dafür und wann ist es gut?

**Comment by chefkoch009** [comment]
Schreib mir bitte eine Mail.

**Comment by martin-afh** [comment]
ok. An [info@punktnetzwerk.net](mailto:info@punktnetzwerk.net)?

**Comment by chefkoch009** [comment]
Ja.
