### ISSUE TITLE
Kann Projektdatei nicht importieren

### ISSUE THREAD

**Issue by DanielH2021** [ioBroker/ioBroker.knx#289]
Bei dem Import der Projektdatei aus ETS 6.0.6 mit KNX Adapter 2.0.18 kommt die Fehlermeldung:

```
knx.0
2023-06-20 17:01:20.862	warn	TypeError: Cannot convert undefined or null to object at Function.values (<anonymous>) at _0x298691 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:257107) at _0x94da9d (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:276478) at _0x94da9d (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:275203) at _0x5d48b8 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:276669) at Object._0x185e90 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:278893) at Object._0xc9884d [as getGAS] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:293985) at _0x203591._0x25b838 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:347195) at _0x203591._0x4b9984 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:339826) at _0x203591.emit (node:events:513:28)

knx.0
2023-06-20 17:01:20.860	warn	States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":1442,"ack":false,"time":1687273280726},"_id":87704710} Cannot convert undefined or null to object
```
Habe nun den Adapter deinstalliert. Den KNX Objektbaum in iobroker entfernt, den Adapter neu installiert und auf 2.0.21 angehoben.
ETS auf 6.1.0 angehoben. Datei neu exportiert.
Es bleibt bei der Fehlermeldung.

Interessant ist, dass nun auch ETS Projektdateien aus dem letzten Jahr beim import die Fehlermeldung bringen. Diese Projektdateien waren seinerzeit mit der Version 2.0.15 importierbar.

**Comment by DanielH2021** [comment]
Mit der KNX Adapterversion 2.0.17 kann ich aktuelle Projekte aus ETS 6.0.6 importieren.
Ein anschließendes Upgrade auf 2.0.21 funktioniert.
D.h. lediglich der Import ab v2.0.18ff. klappt nicht mehr - weder mit ETS 6.0.6 noch mit ETS 6.1.0 Projekten.

**Comment by chefkoch009** [comment]
Kannst du mir das Projekt mal schicken?

**Comment by DanielH2021** [comment]
Gern, an welche Mail Adresse?

**Comment by chefkoch009** [comment]
teste mal bitte die v2.0.22

**Comment by toschi123** [comment]
Hi, ich habe das gleiche Problem und würde die Version 2.0.22 testen. Aber der Adapter läuft dann nicht mehr wenn ich die Github Version installiere. 
startInstance knx.0: cannot find start file!

**Comment by chefkoch009** [comment]
Der Adapter ist ausschließlich über npm installierbar. Also npm -i iobroker.knx@2.0.22

**Comment by toschi123** [comment]
Danke für die Hilfe. Mit 
npm install iobroker.knx@2.0.22
 iobroker upload knx
konnte ich den Adapter aktualisieren und der Import der Projektdatei aus ETS 6.1.0 (Build 5686) funktioniert.

**Comment by chefkoch009** [comment]
Danke für die Rückmeldung. Damit ist der Fall gelöst.
