### ISSUE TITLE
Projektdatei upload funktioniert nicht

### ISSUE THREAD

**Issue by WallE-04** [ioBroker/ioBroker.knx#295]
Ich kann mit der Version 2.0.22 mein aktuelles Projektfile nicht hochladen.
Es gibt keine Fehlermeldung, der Ladefortschritt bleibt kurz vor dem Ende einfach stehen.
Alles am Rapi und ioBroker ist auf aktuellem Stand.

**Comment by chefkoch009** [comment]
Welche ETS Version hast Du? Hast mal „iob u knx“ gemacht?

**Comment by WallE-04** [comment]
Servus,
ich habe die aktuellste ETS 6.1.0 (Build 5686)

iob u knx habe ich gerade versucht, ....ohne erfolg...

Ich habe aber nun doch Log-Einträge dazu gefunden...
***@***.***

Freundliche Grüße

Martin Wallenböck

________________________________
Aumühlstraße 7
3140 Pottenbrunn
Mobil: +43 699 18002358
Mail: ***@***.******@***.***>
________________________________

Von: chefkoch009 ***@***.***>
Gesendet: Donnerstag, 17. August 2023 23:05
An: ioBroker/ioBroker.knx ***@***.***>
Cc: WallE-04 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.knx] Projektdatei upload funktioniert nicht (Issue #295)


Welche ETS Version hast Du? Hast mal "iob u knx" gemacht?

-

**Comment by chefkoch009** [comment]
Danke für die Info. Was steht im log?

**Comment by WallE-04** [comment]
Sorry...hatte einen Screenshot gemacht...der fehlt wohl.

States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":1046,"ack":false,"time":1692306538365},"_id":39417708} Parameter "id" needs to be of type "string" but type "undefined" has been passed

Error: Parameter "id" needs to be of type "string" but type "undefined" has been passed at Function.assertString ***@***.******@***.***/js-controller-adapter/src/lib/adapter/validator.ts:241:19>) at _0xfc53fd.getObject ***@***.******@***.***/js-controller-adapter/src/lib/adapter/adapter.ts:3578:19>) at _0xfc53fd._0x29d2ce (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:396591) at /opt/iobroker/node_modules/iobroker.knx/knx.js:1:390895 at Object._0x2e5cee [as getGAS] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:336997) at _0xfc53fd._0x212876 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:390133) at _0xfc53fd._0x4557b8 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:382648) at _0xfc53fd.emit (node:events:527:28) at _0xfc53fd.emit (node:domain:475:12) at change ***@***.******@***.***/js-controller-adapter/src/lib/adapter/adapter.ts:10989:34>)

**Comment by chefkoch009** [comment]
Hast du irgendwo Sonderzeichen in deinem Projekt? Kannst du mir dein Projekt mal zukommen lassen?

**Comment by WallE-04** [comment]
Also Sonderzeichen hab ich möglicherweise.....bin Gegner von der "undeutschen" Sprache.
IT ist intelligent genug dies zu umschiffen...

Hier meine Export-Datei: Wallenböck - 20230817.knxproj<https://1drv.ms/u/s!AlqlTj8iuOHztNZYFrYiU41rPi6IOA?e=NQFibE>.

DANKE für deine Hilfe!

**Comment by WallE-04** [comment]
Konntest du schon eine Ursache ausmachen?

**Comment by WallE-04** [comment]
Also ich habe nun alle ü/ä/ä/ß aus den Gruppenadressen entfernt. Daran ist es nicht gelegen. Und das hatte in der Vergangenheit ja bisher keine Probleme gemacht.
Die Fehlermeldungen beim Importieren sind immer noch da.
Ich hoffe du kannst hier eine Ursache finden und das fixen.
DANKE!

**Comment by chefkoch009** [comment]
Bin noch dabei.

**Comment by chefkoch009** [comment]
funktioniert es jetzt bei Dir?

**Comment by WallE-04** [comment]
Hi...
Danke der Nachfrage!
Ich denke es hat nach einem Update mal funktioniert....
Hab aber nichts mehr gemacht seit dem...

Und jetzt, bekomme ich eine Fehlermeldung vom Adapter, aber keinen Log-Eintrag...
[Ein Bild, das Text, Screenshot, Display, Schrift enthält.  Automatisch generierte Beschreibung]


[Ein Bild, das Text, Screenshot, Schrift enthält.  Automatisch generierte Beschreibung]

Und bei den GA-Tools ist alles leer...
Wenn ich dann zurück gehe in die Configuration ....sieht der Status so aus....

[Ein Bild, das Text, Screenshot, Schrift enthält.  Automatisch generierte Beschreibung]


Habe gesehen auf GitHub dass es schon die 2.0.26 gibt....
Jep.-...jetzt ists mir klar...ich habe die Tage die ETS auf 6.2.1 upgedated...

Habe heute mit meinem Sohn stundenlang am Raspi gebastelt da irgend was mit diesem node und npm und dem ganzen zeugs nicht gepasst hat....
Nun konnte ich auf 2.0.26 updaten....

Leider habe ich nach dem Import keine Gruppenadressen....

Hier das Log
[Ein Bild, das Text, Screenshot, Reihe, Schrift enthält.  Automatisch generierte Beschreibung]


Danke für deinen Einsatz für dieses Produkt.


Freundliche Grüße

Martin

Von: chefkoch009 ***@***.******@***.***>>
Gesendet: Donnerstag, 28. März 2024 13:31
An: ioBroker/ioBroker.knx ***@***.******@***.***>>
Cc: WallE-04 ***@***.******@***.***>>; Author ***@***.******@***.***>>
Betreff: Re: [ioBroker/ioBroker.knx] Projektdatei upload funktioniert nicht (Issue #295)


funktioniert es jetzt bei Dir?

-

**Comment by WallE-04** [comment]
Habe heute upgedated auf 2.0.27.

Funktioniert nicht

***@***.***


Freundliche Grüße

Martin
________________________________

Betreff: AW: [ioBroker/ioBroker.knx] Projektdatei upload funktioniert nicht (Issue #295)

Hi...
Danke der Nachfrage!
Ich denke es hat nach einem Update mal funktioniert....
Hab aber nichts mehr gemacht seit dem...

Und jetzt, bekomme ich eine Fehlermeldung vom Adapter, aber keinen Log-Eintrag...
[Ein Bild, das Text, Screenshot, Display, Schrift enthält.  Automatisch generierte Beschreibung]


[Ein Bild, das Text, Screenshot, Schrift enthält.  Automatisch generierte Beschreibung]

Und bei den GA-Tools ist alles leer...
Wenn ich dann zurück gehe in die Configuration ....sieht der Status so aus....

[Ein Bild, das Text, Screenshot, Schrift enthält.  Automatisch generierte Beschreibung]


Habe gesehen auf GitHub dass es schon die 2.0.26 gibt....
Jep.-...jetzt ists mir klar...ich habe die Tage die ETS auf 6.2.1 upgedated...

Habe heute mit meinem Sohn stundenlang am Raspi gebastelt da irgend was mit diesem node und npm und dem ganzen zeugs nicht gepasst hat....
Nun konnte ich auf 2.0.26 updaten....

Leider habe ich nach dem Import keine Gruppenadressen....

Hier das Log
[Ein Bild, das Text, Screenshot, Reihe, Schrift enthält.  Automatisch generierte Beschreibung]


Danke für deinen Einsatz für dieses Produkt.


Freundliche Grüße

Martin

Von: chefkoch009 ***@***.******@***.***>>
Gesendet: Donnerstag, 28. März 2024 13:31
An: ioBroker/ioBroker.knx ***@***.******@***.***>>
Cc: WallE-04 ***@***.******@***.***>>; Author ***@***.******@***.***>>
Betreff: Re: [ioBroker/ioBroker.knx] Projektdatei upload funktioniert nicht (Issue #295)


funktioniert es jetzt bei Dir?

-

**Comment by chefkoch009** [comment]
Gibt es irgendwelche Fehlermeldungen?

**Comment by WallE-04** [comment]
Ja...hätte ich als Screenshot angefügt.



2024-05-14 23:24:43.591
warn
Terminated (UNCAUGHT_EXCEPTION): Without reason
[Ein Bild, das Grafiken, Screenshot, Grafikdesign, Schrift enthält.  Automatisch generierte Beschreibung]
knx.0
2024-05-14 23:24:43.589
info
terminating
[Ein Bild, das Grafiken, Screenshot, Grafikdesign, Schrift enthält.  Automatisch generierte Beschreibung]
knx.0
2024-05-14 23:24:43.549
error
Parameter "id" needs to be of type "string" but type "undefined" has been passed
[Ein Bild, das Grafiken, Screenshot, Grafikdesign, Schrift enthält.  Automatisch generierte Beschreibung]
knx.0
2024-05-14 23:24:43.549
error
Error: Parameter "id" needs to be of type "string" but type "undefined" has been passed at Function.assertString ***@***.******@***.***/js-controller-adapter/src/lib/adapter/validator.ts:241:19>) at _0x4104d6.getObject ***@***.******@***.***/js-controller-adapter/src/lib/adapter/adapter.ts:3624:19>) at _0x4104d6._0x3c92c0 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:405326) at /opt/iobroker/node_modules/iobroker.knx/knx.js:1:399615 at Object._0x3033c8 [as getGAS] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:344018) at _0x4104d6._0x79a5d8 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:398877) at _0x4104d6._0x2f1f80 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:389963) at _0x4104d6.emit (node:events:517:28) at _0x4104d6.emit (node:domain:489:12) at change ***@***.******@***.***/js-controller-adapter/src/lib/adapter/adapter.ts:11114:34>)
[Ein Bild, das Grafiken, Screenshot, Grafikdesign, Schrift enthält.  Automatisch generierte Beschreibung]
knx.0
2024-05-14 23:24:43.275
error
unhandled promise rejection: Parameter "id" needs to be of type "string" but type "undefined" has been passed
[Ein Bild, das Grafiken, Screenshot, Grafikdesign, Schrift enthält.  Automatisch generierte Beschreibung]
knx.0
2024-05-14 23:24:43.270
error
Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


Freundliche Grüße

Martin

Von: chefkoch009 ***@***.***>
Gesendet: Dienstag, 14. Mai 2024 23:20
An: ioBroker/ioBroker.knx ***@***.***>
Cc: WallE-04 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.knx] Projektdatei upload funktioniert nicht (Issue #295)


Gibt es irgendwelche Fehlermeldungen?

-

**Comment by Apollon77** [comment]
@WallE-04 Email attachements gehen nicht. Bitte Bilder direkt in GitHub hochladen
