### ISSUE TITLE
Unable to connect MDT IP Interface with iobroker.knx adapte

### ISSUE THREAD

**Issue by FlippiHimself** [ioBroker/ioBroker.knx#320]
Hi,

I already searched the whole internet and I´m pretty stuck.
I´ve got an MDT IP Interface running on 192.168.0.113 and working (at least, I am able to program my knx devices with it, so...)

I installed the knx adapter and set everything up:
IP: 192.168.0.113
PORT: 3671
Physical address: 1.1.6
lokal iobroker-IP: 192.168.0.9

After starting the adapter, i am getting weird errors and the explain much to me...

I started the adapter once without an uploaded ETS and with a uploaded ETS file. In both cases, i get the same problem, not willing to start...

Maybe, anyone can understand the error.log output and give me a hint, where the problem might persist...?

Thx in advance 

2024-08-01 18:50:36.114 - info: host.smarthome-PC instance system.adapter.knx.0 started with pid 4790
2024-08-01 18:50:37.691 - info: knx.0 (4790) starting. Version 2.0.28 in /opt/iobroker/node_modules/iobroker.knx, node: v18.19.0, js-controller: 5.0.19
2024-08-01 18:50:37.810 - warn: knx.0 (4790) No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !
2024-08-01 18:50:37.812 - info: knx.0 (4790) Connecting to knx GW: 192.168.0.113:3671 with phy. Adr: 1.1.6
2024-08-01 18:50:37.817 - info: knx.0 (4790) Debuglevel: 2 3
2024-08-01 18:50:37.819 - info: knx.0 (4790) Event : UDP - listening
2024-08-01 18:50:37.821 - info: knx.0 (4790) Connected - local UDP Server listening on 192.168.0.9:39643
2024-08-01 18:50:37.821 - info: knx.0 (4790) Send : description Request : 06 10 02 03 00 0e 08 01 c0 a8 00 09 9a db sent to 192.168.0.113:3671
2024-08-01 18:50:37.826 - info: knx.0 (4790) Send : searchReqExt Request : 06 10 02 0b 00 14 08 01 c0 a8 00 09 9a db 06 04 01 02 08 06 sent to 192.168.0.113:3671
2024-08-01 18:50:37.826 - info: knx.0 (4790) STATE_SEARCH_EXT_REQUEST : no defined handling for transition from State: STATE_DESCRIPTION_RESPONSE(18) to STATE_SEARCH_EXT_REQUEST(19).
2024-08-01 18:50:37.832 - error: knx.0 (4790) uncaught exception: _0x483e5b[_0x23afe0(...)] is not a function
2024-08-01 18:50:37.832 - error: knx.0 (4790) TypeError: _0x483e5b[_0x23afe0(...)] is not a function
at _0x56350b (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:83864)
at _0x2c39a2 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:97298)
at _0x372871 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:100623)
at _0x9086e4 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:78773)
at Socket. (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:125718)
at Socket.emit (node:events:517:28)
at Socket.emit (node:domain:489:12)
at UDP.onMessage (node:dgram:942:8)
2024-08-01 18:50:37.833 - error: knx.0 (4790) _0x483e5b[_0x23afe0(...)] is not a function
2024-08-01 18:50:37.842 - info: knx.0 (4790) Connection persists.....closing now
2024-08-01 18:50:37.843 - info: knx.0 (4790) ... not able to close connection, because already closed
2024-08-01 18:50:37.843 - info: knx.0 (4790) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_SEARCH_EXT_REQUEST(19) to STATE_NOT_CONNECTED(0).
2024-08-01 18:50:37.843 - info: knx.0 (4790) terminating
2024-08-01 18:50:37.844 - warn: knx.0 (4790) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-08-01 18:50:37.844 - info: knx.0 (4790) ( END ) Sending DISCONNECT_REQUEST : 06 10 02 09 00 10 00 00 08 01 c0 a8 00 09 00 00 ChID : 0 SeqCntIN : 0 SeqCntOUT : 0 msgCode : [object Object]
2024-08-01 18:50:37.844 - info: knx.0 (4790) STATE_DISCONNECT_REQUEST : Transition from State: STATE_NOT_CONNECTED(0) to STATE_DISCONNECT_REQUEST(15) not possible because of cancelled connection.
2024-08-01 18:50:37.844 - info: knx.0 (4790) Connection persists.....closing now
2024-08-01 18:50:37.845 - info: knx.0 (4790) ... not able to close connection, because already closed
2024-08-01 18:50:37.845 - info: knx.0 (4790) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
2024-08-01 18:50:37.847 - info: knx.0 (4790) STATE_DISCONNECT_RESPONSE : from State: STATE_NOT_CONNECTED(0) to STATE_DISCONNECT_RESPONSE(16) ... connection closed
2024-08-01 18:50:37.847 - info: knx.0 (4790) Received DISCONNECT_RESPONSE06 10 02 0a 00 08 00 21
2024-08-01 18:50:37.847 - info: knx.0 (4790) Connection persists.....closing now
2024-08-01 18:50:37.848 - info: knx.0 (4790) ... not able to close connection, because already closed
2024-08-01 18:50:37.848 - info: knx.0 (4790) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
2024-08-01 18:50:38.159 - error: host.smarthome-PC Caught by controller[0]: TypeError: _0x483e5b[_0x23afe0(...)] is not a function
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at _0x56350b (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:83864)
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at _0x2c39a2 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:97298)
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at _0x372871 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:100623)
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at _0x9086e4 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:78773)
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:125718)
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at Socket.emit (node:events:517:28)
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at Socket.emit (node:domain:489:12)
2024-08-01 18:50:38.160 - error: host.smarthome-PC Caught by controller[0]: at UDP.onMessage (node:dgram:942:8)
2024-08-01 18:50:38.160 - error: host.smarthome-PC instance system.adapter.knx.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-08-01 18:50:38.160 - info: host.smarthome-PC Restart adapter system.adapter.knx.0 because enabled
2024-08-01 18:50:38.347 - info: host.smarthome-PC instance system.adapter.knx.0 started with pid 4805
2024-08-01 18:50:40.149 - info: knx.0 (4805) starting. Version 2.0.28 in /opt/iobroker/node_modules/iobroker.knx, node: v18.19.0, js-controller: 5.0.19
2024-08-01 18:50:40.313 - warn: knx.0 (4805) No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !
2024-08-01 18:50:40.316 - info: knx.0 (4805) Connecting to knx GW: 192.168.0.113:3671 with phy. Adr: 1.1.6
2024-08-01 18:50:40.323 - info: knx.0 (4805) Debuglevel: 2 3
2024-08-01 18:50:40.326 - info: knx.0 (4805) Event : UDP - listening
2024-08-01 18:50:40.330 - info: knx.0 (4805) Connected - local UDP Server listening on 192.168.0.9:44961
2024-08-01 18:50:40.331 - info: knx.0 (4805) Send : description Request : 06 10 02 03 00 0e 08 01 c0 a8 00 09 af a1 sent to 192.168.0.113:3671
2024-08-01 18:50:40.338 - info: knx.0 (4805) Send : searchReqExt Request : 06 10 02 0b 00 14 08 01 c0 a8 00 09 af a1 06 04 01 02 08 06 sent to 192.168.0.113:3671
2024-08-01 18:50:40.338 - info: knx.0 (4805) STATE_SEARCH_EXT_REQUEST : no defined handling for transition from State: STATE_DESCRIPTION_RESPONSE(18) to STATE_SEARCH_EXT_REQUEST(19).
2024-08-01 18:50:40.345 - error: knx.0 (4805) uncaught exception: _0x483e5b[_0x23afe0(...)] is not a function
2024-08-01 18:50:40.346 - error: knx.0 (4805) TypeError: _0x483e5b[_0x23afe0(...)] is not a function
at _0x56350b (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:83864)
at _0x2c39a2 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:97298)
at _0x372871 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:100623)
at _0x9086e4 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:78773)
at Socket. (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:125718)
at Socket.emit (node:events:517:28)
at Socket.emit (node:domain:489:12)
at UDP.onMessage (node:dgram:942:8)
2024-08-01 18:50:40.346 - error: knx.0 (4805) _0x483e5b[_0x23afe0(...)] is not a function
2024-08-01 18:50:40.427 - info: knx.0 (4805) Connection persists.....closing now
2024-08-01 18:50:40.428 - info: knx.0 (4805) ... not able to close connection, because already closed
2024-08-01 18:50:40.428 - info: knx.0 (4805) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_SEARCH_EXT_REQUEST(19) to STATE_NOT_CONNECTED(0).
2024-08-01 18:50:40.429 - info: knx.0 (4805) terminating
2024-08-01 18:50:40.429 - warn: knx.0 (4805) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-08-01 18:50:40.429 - info: knx.0 (4805) ( END ) Sending DISCONNECT_REQUEST : 06 10 02 09 00 10 00 00 08 01 c0 a8 00 09 00 00 ChID : 0 SeqCntIN : 0 SeqCntOUT : 0 msgCode : [object Object]
2024-08-01 18:50:40.430 - info: knx.0 (4805) STATE_DISCONNECT_REQUEST : Transition from State: STATE_NOT_CONNECTED(0) to STATE_DISCONNECT_REQUEST(15) not possible because of cancelled connection.
2024-08-01 18:50:40.430 - info: knx.0 (4805) Connection persists.....closing now
2024-08-01 18:50:40.430 - info: knx.0 (4805) ... not able to close connection, because already closed
2024-08-01 18:50:40.430 - info: knx.0 (4805) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
2024-08-01 18:50:40.432 - info: knx.0 (4805) STATE_DISCONNECT_RESPONSE : from State: STATE_NOT_CONNECTED(0) to STATE_DISCONNECT_RESPONSE(16) ... connection closed
2024-08-01 18:50:40.433 - info: knx.0 (4805) Received DISCONNECT_RESPONSE06 10 02 0a 00 08 00 21
2024-08-01 18:50:40.433 - info: knx.0 (4805) Connection persists.....closing now
2024-08-01 18:50:40.433 - info: knx.0 (4805) ... not able to close connection, because already closed
2024-08-01 18:50:40.434 - info: knx.0 (4805) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
2024-08-01 18:50:40.628 - error: host.smarthome-PC Caught by controller[0]: TypeError: _0x483e5b[_0x23afe0(...)] is not a function
2024-08-01 18:50:40.628 - error: host.smarthome-PC Caught by controller[0]: at _0x56350b (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:83864)
2024-08-01 18:50:40.628 - error: host.smarthome-PC Caught by controller[0]: at _0x2c39a2 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:97298)
2024-08-01 18:50:40.628 - error: host.smarthome-PC Caught by controller[0]: at _0x372871 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:100623)
2024-08-01 18:50:40.628 - error: host.smarthome-PC Caught by controller[0]: at _0x9086e4 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:78773)
2024-08-01 18:50:40.629 - error: host.smarthome-PC Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:125718)
2024-08-01 18:50:40.629 - error: host.smarthome-PC Caught by controller[0]: at Socket.emit (node:events:517:28)
2024-08-01 18:50:40.629 - error: host.smarthome-PC Caught by controller[0]: at Socket.emit (node:domain:489:12)
2024-08-01 18:50:40.629 - error: host.smarthome-PC Caught by controller[0]: at UDP.onMessage (node:dgram:942:8)
2024-08-01 18:50:40.629 - error: host.smarthome-PC instance system.adapter.knx.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-08-01 18:50:40.629 - info: host.smarthome-PC Restart adapter system.adapter.knx.0 because enabled
2024-08-01 18:50:48.169 - info: host.smarthome-PC "system.adapter.knx.0" disabled

**Comment by chefkoch009** [comment]
Please try unencrypted connection. The adapter doesn't support it yet.

**Comment by chefkoch009** [comment]
Disable knx secure connection.

**Comment by FlippiHimself** [comment]
Hi. Thanks for the tip! It worked :)

Greetings
