### ISSUE TITLE
Update von 0.8.6 aufwärts nicht möglich

### ISSUE THREAD

**Issue by quinti123** [ioBroker/ioBroker.knx#53]
Hallo,
versuche seit langem meinen Adapter von 0.8.6 auf neuere Versionen umzustellen. Habs mehrfach mit verschiedenen Versionen probiert und immer meine alten Node/NPM/js Versionen im Verdacht gehabt.
Habe nun meinen iobroker unter windows 10 auf neuesten Stand gebracht:
Node 10.15.3
npm 6.4.1
js 1.5.7
Trotzdem noch gleiches verhalten bei Versionen grösser 0.8.6 vom KNX Adapter.
Adapter bleibt gelb nach start. Sobald ich versuche einen state zu ändern ist das log voll mit Fehlermeldungen

2019-03-25 11:35:55.720  - (info): iobroker upgrade knx
2019-03-25 11:35:56.345  - (info): iobroker Update knx from @0.8.6 to @1.0.20
2019-03-25 11:35:56.807  - (info): iobroker NPM version: 6.4.1
2019-03-25 11:35:57.264  - (info): iobroker npm install iobroker.knx@1.0.20 --production --save --prefix "C:/ioBroker" (System call)
2019-03-25 11:35:59.339  - (info): iobroker npm 
2019-03-25 11:35:59.339  - (info): iobroker WARN deprecated dgram@1.0.1: npm is holding this package for security reasons. As it's a core Node module, we will not transfer it over to other users. You may safely remove the package from your dependencies.
2019-03-25 11:36:01.329  - (info): iobroker npm install --production (System call) in "C:/ioBroker/node_modules/iobroker.knx"
2019-03-25 11:36:02.789  - (info): iobroker npm
2019-03-25 11:36:02.789  - (info): iobroker  WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
2019-03-25 11:36:03.190  - (info): iobroker npm
2019-03-25 11:36:03.190  - (info): iobroker  WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2019-03-25 11:36:04.314  - (info): iobroker npm
2019-03-25 11:36:04.314  - (info): iobroker  WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
2019-03-25 11:36:05.319  - (info): iobroker npm
2019-03-25 11:36:05.319  - (info): iobroker  WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2019-03-25 11:36:06.400  - (info): iobroker npm
2019-03-25 11:36:06.400  - (info): iobroker  WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2019-03-25 11:36:06.514  - (info): iobroker npm 
2019-03-25 11:36:06.515  - (info): iobroker WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
2019-03-25 11:36:08.450  - (info): iobroker npm
2019-03-25 11:36:08.451  - (info): iobroker  notice created a lockfile as package-lock.json. You should commit this file.
2019-03-25 11:36:08.870  - (info): iobroker got C:/ioBroker/node_modules/iobroker.knx/admin
2019-03-25 11:36:08.878  - (info): host.KELLER object change system.adapter.knx.0
2019-03-25 11:36:08.878  - (info): host.KELLER "system.adapter.knx.0" disabled
2019-03-25 11:36:08.878  - (info): host.KELLER stopInstance system.adapter.knx.0
2019-03-25 11:36:08.878  - (info): host.KELLER stopInstance system.adapter.knx.0 killing pid 1648
2019-03-25 11:36:08.886  - (info): host.KELLER object change system.adapter.knx.0
2019-03-25 11:36:08.886  - (info): host.KELLER "system.adapter.knx.0" enabled
2019-03-25 11:36:08.889  - (info): host.KELLER instance system.adapter.knx.0 started with pid 11896
2019-03-25 11:36:08.892  - (warn): host.KELLER instance system.adapter.knx.0 terminated due to SIGTERM
2019-03-25 11:36:08.892  - (info): host.KELLER instance system.adapter.knx.0 terminated with code null ()
2019-03-25 11:36:08.893  - (info): iobroker Adapter "system.adapter.knx.0" restarted.
2019-03-25 11:36:08.894  - (info): iobroker upload [7] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/zip/zip.js zip/zip.js application/javascript
2019-03-25 11:36:08.914  - (info): iobroker Update "system.adapter.knx.0"
2019-03-25 11:36:08.918  - (info): host.KELLER object change system.adapter.knx.0
2019-03-25 11:36:08.920  - (info): host.KELLER instance system.adapter.knx.0 started with pid 10564
2019-03-25 11:36:08.965  - (info): iobroker upload [6] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/zip/zip-ext.js zip/zip-ext.js application/javascript
2019-03-25 11:36:09.022  - (info): iobroker upload [5] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/zip/z-worker.js zip/z-worker.js application/javascript
2019-03-25 11:36:09.080  - (info): iobroker upload [4] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/zip/inflate.js zip/inflate.js application/javascript
2019-03-25 11:36:09.142  - (info): iobroker upload [3] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/words.js words.js application/javascript
2019-03-25 11:36:09.199  - (info): iobroker upload [2] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/knx.png knx.png image/png
2019-03-25 11:36:09.199  - (debug): knx.0 objectDB connected
2019-03-25 11:36:09.204  - (debug): knx.0 statesDB connected
2019-03-25 11:36:09.217  - (info): knx.0 starting. Version 1.0.20 in C:/ioBroker/node_modules/iobroker.knx, node: v10.15.3
2019-03-25 11:36:09.215  - (debug): knx.0 objectDB connected
2019-03-25 11:36:09.222  - (debug): knx.0 statesDB connected
2019-03-25 11:36:09.232  - (info): knx.0 starting. Version 1.0.20 in C:/ioBroker/node_modules/iobroker.knx, node: v10.15.3
2019-03-25 11:36:09.257  - (info): iobroker upload [1] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/index_m.html index_m.html text/html
2019-03-25 11:36:09.338  - (info): knx.0 knx license is OK.
2019-03-25 11:36:09.342  - (info): knx.0 knx license is OK.
2019-03-25 11:36:09.345  - (info): knx.0 Connecting to knx GW:  192.168.101.9:3671   with phy. Adr:  1.1.128
2019-03-25 11:36:09.340  - (info): knx.0 Connecting to knx GW:  192.168.101.9:3671   with phy. Adr:  1.1.128
2019-03-25 11:36:09.397  - (info): iobroker upload [0] knx.admin C:/ioBroker/node_modules/iobroker.knx/admin/index.html index.html text/html
2019-03-25 11:36:09.491  - (info): iobroker Adapter "knx" updated
2019-03-25 11:36:09.500  - (info): iobroker exit 0
2019-03-25 11:36:21.929  - (debug): knx.0 system.adapter.admin.0: logging true
2019-03-25 11:36:21.930  - (debug): knx.0 system.adapter.admin.0: logging true
2019-03-25 11:36:51.948  - (debug): knx.0 system.adapter.admin.0: logging false
2019-03-25 11:36:51.948  - (debug): knx.0 system.adapter.admin.0: logging false
2019-03-25 11:36:56.964  - (error): knx.0 message knx.0.Schalten.Schalten.Licht_Arbeitszimmer_(J) [object Object] Cannot read property 'write' of undefined
2019-03-25 11:36:56.965  - (error): knx.0 message knx.0.Schalten.Schalten.Licht_Arbeitszimmer_(J) [object Object] Cannot read property 'write' of undefined
2019-03-25 11:36:56.967  - (error): knx.0 TypeError: Cannot read property 'write' of undefined
    at Object.stateChange (C:\ioBroker\node_modules\iobroker.knx\knx.js:79:2708)
    at Object.change (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3425:37)
    at Socket.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:52:30)
    at Socket.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-emitter\index.js:133:20)
    at Socket.onevent (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:278:10)
    at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
    at Manager.<anonymous> (C:\ioBroker\node_modules\component-bind\index.js:21:15)
    at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-emitter\index.js:133:20)
    at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:345:8)
    at Decoder.<anonymous> (C:\ioBroker\node_modules\component-bind\index.js:21:15)
2019-03-25 11:36:56.968  - (error): knx.0 TypeError: Cannot read property 'write' of undefined
    at Object.stateChange (C:\ioBroker\node_modules\iobroker.knx\knx.js:79:2708)
    at Object.change (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3425:37)
    at Socket.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:52:30)
    at Socket.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-emitter\index.js:133:20)
    at Socket.onevent (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:278:10)
    at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
    at Manager.<anonymous> (C:\ioBroker\node_modules\component-bind\index.js:21:15)
    at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-emitter\index.js:133:20)
    at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:345:8)
    at Decoder.<anonymous> (C:\ioBroker\node_modules\component-bind\index.js:21:15)

**Comment by chefkoch009** [comment]
Importiere bitte das knxproj einmal neu.

**Comment by quinti123** [comment]
nach update auf 1.0.20 und neuem import der knxproj Datei leider immer noch der gleiche Fehler

**Comment by chefkoch009** [comment]
Kannst Du mal die RAW vom knx.0 message knx.0.Schalten.Schalten.Licht_Arbeitszimmer_(J) posten?

**Comment by quinti123** [comment]
`{
  "from": "system.adapter.knx.0",
  "ts": 1554213952936,
  "user": "system.user.admin",
  "common": {
    "name": "Licht Arbeitszimmer (J)",
    "type": "boolean",
    "role": "switch",
    "desc": "DPT-1",
    "read": false,
    "write": true,
    "min": false,
    "max": true,
    "smartName": {
      "de": "Arbeitszimmer Licht",
      "smartType": "LIGHT"
    },
    "mobile": {
      "admin": {
        "visible": true
      }
    }
  },
  "native": {
    "dpt": "DPT1.000",
    "address": "1/0/10",
    "addressRefId": "P-024F-0_GA-38",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Schalten.Schalten.Licht_Arbeitszimmer_(J)",
  "type": "state"
}`

**Comment by chefkoch009** [comment]
Welche ETS Version hast du? Ab 5.7 funktioniert es nicht mehr...ich arbeite mit Hochdruck am Update.

**Comment by chefkoch009** [comment]
Keine Rückmeldung, gehe davon aus das Problem gelöst ist.
