### ISSUE TITLE
crash during import

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.knx#65]
Hi,

I just updated to 1.0.31.
Because writing to some GAs did not work anymore (somehow the adapter only did send GroupValueRead request instead of issuing commands, like it did before. I'll create a new issue for that, when import works again and if the problem persists) I tried to reimport my project. 
This fails with the attached log.

I can send you my project file, if you want. I was using ETS 5.7.1 for some time and imported the project with older versions of the adapter without obvious issues.

[knx-error.log](https://github.com/ioBroker/ioBroker.knx/files/3537330/knx-error.log)

**Comment by chefkoch009** [comment]
I only analized ets5.7.2 Exports. I don‘t know what was changed in 5.7.1, because i don‘t have such a project file. There are two importers in the Adapter. Ohne for projects till 5.7.1 which i left as it is and the Second one for Version 5.7.2 and above.

**Comment by Garfonso** [comment]
Does the error come from the import itself? Or maybe from some of the ifrastructure around the older importert? 
I tried again with an older export which definitefily was successfully imported using 1.0.20 and it crashes with the same error.

**Comment by Garfonso** [comment]
I updated to ets5.7.2 and exported the (unchanged) project again and then the import works fine again.
If you are sure that it is related to ets5.7.1 and not to the infrastructure around the old importer we can close the issue then.

**Comment by de-jens** [comment]
I have ETS 5.7.2 Build 743.
When i'm importing the .knxproj i always have the same error.
I tiered different versions of iobroker.knx but it is always the same.
It would be nice i the error log would show the name off the GA where it fails.

2019-10-20 20:05:14.986  - debug: knx.0 knx.js Zeitmessung parseProject STOPP :
2019-10-20 20:05:15.004  - info: node-red.0 node-red exited with 0
2019-10-20 20:05:14.987  - debug: knx.0 knx.js Time fillProject start.
2019-10-20 20:05:15.087  - error: knx.0 message messagebox.system.adapter.knx.0 [object Object] Cannot read property 'unit' of undefined
2019-10-20 20:05:15.089  - error: knx.0 TypeError: Cannot read property 'unit' of undefined
    at _0x17af3c (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:19002)
    at _0x4e8f50 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:21651)
    at Object._0x228177 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:40154)
    at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13770)
    at _0x601f89 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8157)
    at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:6848)
    at Adapter.emit (events.js:198:13)
    at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3681:34)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)

**Comment by chefkoch009** [comment]
is fixed in new version
