### ISSUE TITLE
TypeError: Cannot read property 'knx.0.Umwelt.Umwelt_Helligkeit.[...]' of null

### ISSUE THREAD

**Issue by ThomasBahn** [ioBroker/ioBroker.knx#68]
Beim Import aus der KNXPROJ-Datei oder kurz danach:

knx.0 | 2019-08-27 13:10:11.432 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
-- | -- | -- | --
knx.0 | 2019-08-27 13:10:11.432 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
knx.0 | 2019-08-27 13:10:11.432 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2019-08-27 13:10:11.432 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2019-08-27 13:10:11.432 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
knx.0 | 2019-08-27 13:10:11.432 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2019-08-27 13:10:11.432 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2019-08-27 13:10:11.432 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
knx.0 | 2019-08-27 13:10:11.432 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3706:37)
knx.0 | 2019-08-27 13:10:11.432 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:79:1335)
knx.0 | 2019-08-27 13:10:11.432 | error | TypeError: Cannot read property 'knx.0.Umwelt.Umwelt_Helligkeit.Helligkeit_WERT_Gesamthelligkeit_BM-A1a_Garage_außen' of null
knx.0 | 2019-08-27 13:10:11.431 | error | message knx.0.Umwelt.Umwelt_Helligkeit.Helligkeit_WERT_Gesamthelligkeit_BM-A1a_Garage_außen null Cannot read property 'knx.0.Umwelt.Umwelt_Helligkeit.Helligkeit_WERT_Gesamthelligkeit_BM-A1a_Garage_au

Immer wieder für verschiedene Objekte (Log ist rausgescrollt).

**Comment by ThomasBahn** [comment]
Sorry, hat länger gedauert. Wo du immer so schnell geholfen hast, habe ich jetzt ein schlechtes Gewissen.  ;-)

Ich habe einmal über die vorhandenen Objekte "drüber importiert" und einmal die Objekte vorher gelöscht und neu importiert. Beide Male trat der Fehler in der Version 1.0.33 nicht mehr auf.
