### ISSUE TITLE
Import Problem min of undefined

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#76]
Probleme bei einem 5.7.2 import mit 1.0.36 und js-controler 2.0.34 :

Es wäre ein try catch gut der ausgibt welche GA failed und trotzdem weiter importiert.

`
2019-10-20 22:19:15.449	warn	at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4501:34)
knx.0	2019-10-20 22:19:15.449	warn	at Adapter.emit (events.js:211:7)
knx.0	2019-10-20 22:19:15.449	warn	at emitOne (events.js:116:13)
knx.0	2019-10-20 22:19:15.449	warn	at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:6848)
knx.0	2019-10-20 22:19:15.449	warn	at _0x601f89 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8157)
knx.0	2019-10-20 22:19:15.449	warn	at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13770)
knx.0	2019-10-20 22:19:15.449	warn	at Object._0x228177 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:40114)
knx.0	2019-10-20 22:19:15.449	warn	at _0x486492 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:15343)
knx.0	2019-10-20 22:19:15.449	warn	at _0x3d0a60 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:14982)
knx.0	2019-10-20 22:19:15.449	warn	at _0x17ceb3 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:7791)
knx.0	2019-10-20 22:19:15.449	warn	(16839) TypeError: Cannot read property 'min' of undefined
knx.0	2019-10-20 22:19:15.437	warn	(16839) States pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":488,"ack":false,"time":157160275
`

**Comment by TA2k** [comment]
Mit 1.0.37 das selbe Problem:

2020-02-23 20:31:00.927 - warn: knx.0 (664) States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":152,"ack":false,"time":1582486260208},"_id":61078536} Cannot read property 'min' of undefined
--
2020-02-23 20:31:01.007 - warn: knx.0 (664) TypeError: Cannot read property 'min' of undefined

**Comment by TA2k** [comment]
fixed with 1.0.39
