### ISSUE TITLE
Import problem range of undefined

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.knx#77]
Hi,

I get the following error with 1.0.36 on import. I changed just minimal stuff in my KNX project (and also tried an old version which of the project). I switched to earlier versions one by one getting the same error. Import then worked on 1.0.31 without issues.
ETS is 5.7.2 build 743.

I can provide the project file if needed.

`
2019-11-03 19:38:44.085  - debug: knx.0 (27799) knx.js Time fillProject start.
2019-11-03 19:38:44.533  - warn: knx.0 (27799) States pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":733,"ack":false,"time":1572806324078},"_id":76583016} Cannot read property 'range' of undefined
2019-11-03 19:38:44.535  - warn: knx.0 (27799) TypeError: Cannot read property 'range' of undefined
    at _0xacf512 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:13201)
    at _0x388c47 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:14653)
    at Object._0x553d25 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38498)
    at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13381)
    at _0x2c8a22 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8356)
    at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:7023)
    at Adapter.emit (events.js:198:13)
    at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4717:34)
    at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:223:41)
    at runCallback (timers.js:705:18)
`

**Comment by chefkoch009** [comment]
Should be solved with current version.
