### ISSUE TITLE
Import Problem property '_id' of undefined

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#85]
ETS 5.7.4
KNX 1.0.37

Import Fehler:

warn: knx.0 (11699) States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":438,"ack":false,"time":1582488962405},"_id":61078825} Cannot read property '_id' of undefined
--
2020-02-23 21:16:03.161 - warn: knx.0 (11699) TypeError: Cannot read property '_id' of undefined
at _0x51ba97 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:12289)
at /opt/iobroker/node_modules/iobroker.knx/knx.js:80:8938
at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13615)
at _0x2aafe9 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8351)
at Adapter. (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:6963)
at Adapter.emit (events.js:198:13)
at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4808:34)
at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:227:41)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)

**Comment by chefkoch009** [comment]
fixed in Version 1.0.38

**Comment by TA2k** [comment]
ETS 5.7.4
KNX 1.0.38

Bitte handle im try catch das der import vorgang fortgesetzt wird und nicht abgebrochen wird.

2020-02-29 22:39:20.495 - warn: knx.0 (639) States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":150,"ack":false,"time":1583012359781},"_id":49679257} Cannot read property '_id' of undefined
--
2020-02-29 22:39:20.513 - warn: knx.0 (639) TypeError: Cannot read property '_id' of undefined
at _0x51ba97 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:12289)
at /opt/iobroker/node_modules/iobroker.knx/knx.js:80:8938
at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13615)
at _0x2aafe9 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8351)
at Adapter. (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:6963)
at Adapter.emit (events.js:198:13)
at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4808:34)
at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:227:41)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)

**Comment by chefkoch009** [comment]
kann ich bitte mal das Projekt haben?

**Comment by TA2k** [comment]
habe ein seperates issue angelegt #86
